### ISSUE TITLE
Customise "Design (1)" addon tab with a count

### ISSUE THREAD

**Issue by didoesdigital** [pocka/storybook-addon-designs#107]
**Is your feature request related to a problem? Please describe.**
Some stories contain design assets and some do not and the only way to know is to select the Design addon tab and see if it is empty or not. It would be more efficient to see the number of design assets linked as a count in the tab name. 

**Describe the solution you'd like**
Let consumers customise the tab name.

**Describe alternatives you've considered**
By default, show the count of design assets i.e. show (1) when the tab contains 1 design asset and (0) when it contains none.

**Design types**

- [x] `figma`
- [x] `experimental-figspec`
- [x] `link`
- [x] `image`
- [x] `iframe`

**Additional context**

Current:

![image](https://user-images.githubusercontent.com/2476974/122161675-73139e00-ceb5-11eb-8243-6b8843321f96.png)

Desired:

![design count](https://user-images.githubusercontent.com/2476974/122161800-b2da8580-ceb5-11eb-85b5-10a667e4bfea.png)

**Comment by pocka** [comment]
It seems we can customize tab titles since Storybook v6.0. Here is the source code for Controls Addon.
https://github.com/storybookjs/storybook/blob/c6d9c7089e26549bd0a5f96a801a8757b6e961b7/addons/controls/src/register.tsx#L10-L15

Probably we can archive this feature request with the `title()` API and [`useParameters`](https://github.com/storybookjs/storybook/blob/adca8e192d7cb24b0547b1135754a70fb09efbf3/lib/api/src/index.tsx#L357-L362).

**Comment by pocka** [comment]
v6.1.0
