### ISSUE TITLE
Drag capability for experimental-figspec

### ISSUE THREAD

**Issue by missi2402** [pocka/storybook-addon-designs#125]
The package has a different approach for scrolling and zooming between 'figma' and 'experimental-figspec' types.

Is it possible to add the ability to drag the design for 'experimental-figspec'?
I can't do horizontal scroll except to use the zoom and indicate the direction with the mouse.
For example, it would be great to be able to allow the design to be dragged when the CTRL (or Shift) button is pressed.

**Design types**
- [X] `experimental-figspec`

I apologize in advance if I missed such an opportunity somewhere and I will be grateful for the hint.
Thanks for the great package and for this experimental part!

**Comment by pocka** [comment]
You can pan around your design by dragging while holding <kbd>Space</kbd> key 👍 
https://github.com/pocka/figspec/pull/9

> The package has a different approach for scrolling and zooming between 'figma' and 'experimental-figspec' types.

Yes, because Figspec aims to provide a similar UI experience to Figma (the editor) rather than to Figma Live Embed Kit (the iframe preview we use for `type: "figma"`). Therefore, I'm willing to accept a PR that fixes behaviors not aligning with Figma (the editor).

**Comment by missi2402** [comment]
This tip helped me a lot, thanks @pocka!
