### ISSUE TITLE
dynamically change the figma design when control variable change

### ISSUE THREAD

**Issue by aelbore** [pocka/storybook-addon-designs#142]
**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
> A clear and concise description of what you want to happen.

I need a feature that changes the figma design base on the control variable, basically for example if i change a theme it should change the figma design

**Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

**Design types**

- [x] `figma`
- [x] `figspec`
- [ ] `link`
- [ ] `image`
- [ ] `iframe`

**Additional context**
> Add any other context or screenshots about the feature request here.

**Comment by pocka** [comment]
Is it possible? 🤔  The parameters, which addons use for their inputs, are [static](https://github.com/storybookjs/storybook/issues/13079#issuecomment-725387644). AFAIK, neither users nor an addon can update parameters based on Args.

Even if it's possible, I think it might cause degraded performance or rendering problems due to frequent updates.

If you have frame/file variations, I recommend you to put an array of objects to the `design` parameter along with `name` properties ([example](https://pocka.github.io/storybook-addon-designs/?path=/story/docs-advanced-usage--set-tab-names), [docs](https://pocka.github.io/storybook-addon-designs/?path=/docs/docs-advanced-usage--embed-multiple-designs#embed-multiple-designs)).

---

Closing as a workaround exists and performance concern. Feel free to reopen (or comment) if you have any idea to address these problems.
