### ISSUE TITLE
Hide design tab when no design

### ISSUE THREAD

**Issue by ladislas14** [pocka/storybook-addon-designs#143]
**Describe the solution you'd like**
Currently, we are able to use tab instead of panel, which is a really nice feature. But in case there is no design provided, the design tab is still shown, saying that there is no design found.

So for pure doc page (for instance Contribute, Changelog pages), it's weird to have a Design tab whereas it is not Components documentation pages. 

It would be nice to either be able to hide the design tab with something like this :

```tsx
<Meta
    title="Contribute"
    parameters={{
        viewMode: 'docs',
        previewTabs: {
            canvas: {hidden: true},
            design: {hidden: true}
        }
    }}
/>
```

or to automatically hide Design tab if no design is provided.

**Design types**

- [x ] `figma`
- [x ] `figspec`
- [x ] `link`
- [x ] `image`
- [x ] `iframe`

Thanks a lot !

**Comment by pocka** [comment]
@ladislas14 
According to [the official document](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#reordering-docs-tab-first), you can access any tab by passing panel name as a key. Since this addon registers itself with panel name `STORYBOOK_ADDON_DESIGNS/panel`, the below parameter hides the `Design` tab. (tested the code in `packages/examples-tab` directory by adding the parameter via `addParameters` in `.storybook/preview.js`)

```js
previewTabs: {
  "STORYBOOK_ADDON_DESIGNS/panel": { hidden: true }
}
```

I'm going to add an export for the panel name for convenience (PR welcome).

**Comment by pocka** [comment]
I added an example and docs for the feature. The `PanelName` export will be available in the next major or minor version.
https://pocka.github.io/storybook-addon-designs/tab/?path=/docs/docs-advanced-usage-configure-tab--sample
