### ISSUE TITLE
Add scaling capabilities to type: "figma"

### ISSUE THREAD

**Issue by Philzen** [pocka/storybook-addon-designs#147]
**Is your feature request related to a problem? Please describe.**
When including figma designs, sometimes one only has a link to a separate node (e.g. a Button) or simply only wants to show that single element in the design preview. When adding that node, it is currently stretched to the full width of the tab, i.e. the button design gets displayed like several hundred pixels wide and tall, instead of showing the original, intended size.

**Describe the solution you'd like**
It would be great to have an option (such as the `scale` option for images) that has an option (which IMHO should be the default) to show the design dimension as originally conceived in the figma design. Possible list of options:
- `scale: "original"` or `scale: 1` → the original size in pixels as defined in the figma design. This is the main feature i'm looking for.
- `scale: "fit"` or `scale: 0` → scales to the available space in the tab (the current behaviour)
- `scale: Number` → similar to the way it works on images, where `2` would make it display twice the size as defined in the figma design

**Describe alternatives you've considered**
Currently, i am unaware of any feasible workaround for this problem. When using the prototype view, it actually shows the correct original size – however, not every element included in a story may be available on a seperate prototype slide (which is the case with the design i'm currently working on). Also prototype view is extremely slow to load up.
There may be a way to experiment with the decorator, which i want to look into, but then again that is unlikely to reliably (without individual configuration for each and every group of stories) yield an exact, original size preview.

**Design types**

- [x] `figma`
- [ ] `figspec` (maybe but i don't have an access to test)
- [ ] `link`
- [ ] `image`
- [ ] `iframe`

**Comment by pocka** [comment]
Unfortunately, you can't change the behavior of `type: "figma"` embeds, because it just renders an iframe. The rendered content, [Figma live embed kit](https://www.figma.com/developers/embed), does not have parameters to configure how it's rendered. If you want the scaling feature, I'd recommend you to ask for Figma (probably [the "Share an idea" category in their official forum](https://forum.figma.com/c/share/12) is the best place?)

I'd like to add an option if Figma implements the feature in their live embed kit.

> Currently, i am unaware of any feasible workaround for this problem. When using the prototype view, it actually shows the correct original size – however, not every element included in a story may be available on a seperate prototype slide (which is the case with the design i'm currently working on). Also prototype view is extremely slow to load up.
There may be a way to experiment with the decorator, which i want to look into, but then again that is unlikely to reliably (without individual configuration for each and every group of stories) yield an exact, original size preview.

I think the prototype embed is the only workaround...
