### ISSUE TITLE
It takes a while to load figma design

### ISSUE THREAD

**Issue by michaelscraft** [pocka/storybook-addon-designs#151]
### Affected design types

- [X] figma
- [ ] figspec
- [ ] link
- [ ] image
- [ ] iframe

### Describe the bug

Thank you for this addon ❤️

I need to wait for like 10 -15 minutes for figma design to appear.
Any idea why it's taking so long?

Browser: Brave
System: Mac OS
Adblockers: everything off

![Screen Shot 2022-05-07 at 1 50 40 AM](https://user-images.githubusercontent.com/22564070/167242576-6450295d-e2aa-4ede-80be-b0aca6ee0a3f.png)

![render](https://user-images.githubusercontent.com/22564070/167240972-cecf1880-ef20-48ec-a8b4-9f41e9003abf.gif)

### How to reproduce the bug?

Followed the instructions for basic setup

### Expected behaviour

Should show Figma design 

### Environment

- [x] Chrome / Chromium / Chromium based browsers
- [ ] Firefox
- [ ] macOS Safari
- [ ] iOS Safari
- [ ] Samsung Internet
- [ ] Other

### Affected versions

6.2.1

### Storybook versions

"@storybook/vue3": "6.4.22"

**Comment by michaelscraft** [comment]
![Screen Shot 2022-05-07 at 1 50 40 AM](https://user-images.githubusercontent.com/22564070/167242562-363f80a6-044c-44e2-9a14-dde8026be97f.png)

**Comment by pocka** [comment]
The `type: "figma"` uses [Figma Live Embed Kit](https://www.figma.com/developers/embed), which is their "embed view" in an `<iframe>` element.

To test whether this performance degradation is because of this addon and/or of surrounding elements, try opening the `<iframe>`'s URL in a new tab. It seems Brave on MacOS does not allow users to open a context menu even with <kbd>⇧ Shift</kbd>, so you need to inspect the DOM tree and grab the value of `src` attribute.

If the loading performance is bad in a dedicated tab too, then please report a bug to Figma team (or Figma Community?).

**Comment by michaelscraft** [comment]
Thank you! It looks like it's a browser-related issue 🤨. Chrome and Safari load iframe URL almost instantly while Brave gets stuck (all adblockers off) with all network requests 200. Thanks for your help!
