### ISSUE TITLE
React Native / RN Web support

### ISSUE THREAD

**Issue by elie222** [pocka/storybook-addon-designs#58]
Great package. Wondering if there are plans to support React Native (or Web) similar to how actions, knobs and notes addons support it.

**Comment by pocka** [comment]
Unfortunately, from what I see from [SB docs](https://storybook.js.org/docs/guides/guide-react-native/#on-device-addons) and [addon-ondevice-knobs' source code](https://github.com/storybookjs/storybook/blob/master/addons/ondevice-knobs/src/GroupTabs.js), we cannot reuse existing components (= react-dom components). Since there is [an option to run non-onDevice-addons](https://storybook.js.org/docs/guides/guide-react-native/#browser-addons), I have no plan to implement it by myself, currently 😔 Managing same purpose multi codebase is hard...

For RN Web, it should work until you use a Storybook for React (or Vue, React... every framework other than RN).
