### ISSUE TITLE
Improved embed for Figma with token values

### ISSUE THREAD

**Issue by yannbf** [pocka/storybook-addon-designs#70]
When using Figma, it's pretty awesome to see the size, spacings, tokens in general of the component:
![image](https://user-images.githubusercontent.com/1671563/93896348-1b168500-fcf1-11ea-9cb2-bd0821654b8e.png)

I'm wondering if it's possible to bring that kind of info to the addon as well. Maybe using Figma API? I would definitely be willing to contribute to this if that's a possible feature!

**Comment by pocka** [comment]
Probably 👍 With Figma API, we can retrieve nodes meta, rendered images, etc... I'm not sure how easy to build a preview, though.

I once implemented and [reverted](https://github.com/pocka/storybook-addon-designs/commit/ee4fe3f58e323eb8d82a4ab8e729b869303167fb) token auth because of official private embed support and security consideration.

To call the Figma APIs, we need to embed a Figma API token into bundled code; anyone who has access to the Storybook can inspect and obtain the token! So I think creating a Figma preview server, which uses Figma API and renders detailed preview, is more robust and secure than a frontend preview-ing. (Or Figma makes the Live Embed Kit more functional... I don't know it's possible.)

**Comment by yannbf** [comment]
What about using tokens instead? And store them in an env file like it's done with [storybook-zeplin](https://github.com/mertkahyaoglu/storybook-zeplin). This way it should work fine locally and in private networks.. And if people really want to have it public they accept the fact that the api key can be read on client side.

I'm not sure about the preview server idea that you mentioned, but with the api + token I think it's quite achievable to add such functionality!

**Comment by pocka** [comment]
Ah sorry, I meant [Access tokens](https://www.figma.com/developers/api#access-tokens), not OAuth :mask:

> This way it should work fine locally and in private networks.. And if people really want to have it public they accept the fact that the api key can be read on client side.

Great strategy. True, a warning and "do it in your risk" message may be enough.

**Comment by pocka** [comment]
For anyone curious about the status of this issue, you can see it here: https://github.com/pocka/storybook-addon-designs/projects/4

![dev pocka io_6006__path=_story_docs-figma-examples--embed-frame](https://user-images.githubusercontent.com/13316015/95560409-37862180-0a54-11eb-89e3-aa01a49f6743.png)

**Comment by yannbf** [comment]
@pocka that looks incredible already! If you want assistance let me know, I'd like to help!

**Comment by johmike** [comment]
@pocka Is the current project usable?

**Comment by pocka** [comment]
Not yet. I'll publish [the package](https://github.com/pocka/figspec) after fixing noticeable bugs, then add an integration to that.

**Comment by pocka** [comment]
I've just published `storybook-addon-designs@v6.0.0-alpha.1`, which includes the enhanced Figma preview powered by Figspec. To try it, change `type: "figma"` to `type: "experimental-figspec"` and add `accessToken` property. Refer to the below link for more!

https://storybook-addon-designs-f8z5gt8iw.vercel.app/?path=/story/docs-figma-figspec-readme--page

As I overusing "experimental", the Figspec module is still in active development (or incomplete, to say honestly.) If you find a bug in the preview, please file an issue on [Figspec repository](https://github.com/pocka/figspec/issues) or send a Pull Request!

I'll close this issue on the v6.0 stable release.

**Comment by hazem3500** [comment]
Looks awesome 🎉, will this be converted to a Docs block?

**Comment by pocka** [comment]
@hazem3500 
Not yet, I thought it's better to implement Docs Block once the basic usage is stabilized. (e.g. whether to add global token registration)

Since Docs Blocks are just React Component, it's very easy to create one. If you are interested in the enriched Figma Doc block, please add a reaction to the comment or send a PR!

**Comment by hazem3500** [comment]
Cool, I'll try sending a PR soon!

thanks @pocka for your great work 😄

**Comment by pocka** [comment]
Closing as design type `experimental-figspec` is now available at v6.0.0.

If you encountered bugs or have an idea for improvements, please open a new issue.

**Comment by reshu0408** [comment]
Hey @pocka I am looking to build similar kind of addon. But the links you have pointed in the comments above throw 404. Would it be possible for you to point me to the Document how can i use this addon?

**Comment by pocka** [comment]
Maybe the link became dead on the repository migration?
Anyway, this is the link for the the latest doc: <https://storybookjs.github.io/addon-designs/?path=/docs/docs-figma-figspec-readme--docs>
