### ISSUE TITLE
Remove "loading..." when asset has been loaded

### ISSUE THREAD

**Issue by iwan-uschka** [pocka/storybook-addon-designs#81]
I am using `type: "iframe"` to load image assets. Reason: `type: "image"` disables scrolling which doesn't make sense in my case. When using `type: "iframe"` a loading label is placed behind the iframe itself. If the content of the iframe doesn't fit the full width or height you can see the loading label which can be confusing.

An alternative could be to add an option to `type: "image"` to enable scrolling and disable offset :)

**Comment by pocka** [comment]
The remaining `loading...` label is due to my laziness... 🤦  It's visible when the site has no background color. I remember I noticed it at some time but it went off my mind then. It should be hide when the iframe content is loaded.

> type: "image" disables scrolling which doesn't make sense in my case.

I don't think the addon prevents scrolling. The addon panel is not scrollable by default. For `type: "image"` preview, you can pan around by click-and-drag.

**Comment by iwan-uschka** [comment]
> For type: "image" preview, you can pan around by click-and-drag

True. Not yet noticed :)

Thanks for your response and for looking into it!

**Comment by pocka** [comment]
Fixed in v5.4.4.

- [Test story](https://storybook-addon-designs-f7jtphfqw.vercel.app/?path=/story/tests-issues-81--hide-loading-placeholder-when-loaded)
- [CHANGELOG](https://github.com/pocka/storybook-addon-designs/blob/master/CHANGELOG.md#544---2021-02-18)

**Comment by iwan-uschka** [comment]
Thx :)
