### ISSUE TITLE
Using a global parameter causes refresh / HMR issues

### ISSUE THREAD

**Issue by shamilovtim** [pocka/storybook-addon-designs#92]
Inside of preview.js add:

```javascript
export const parameters = {
  design: { accessToken: 'your token' }
};
```

The Figma file will load if the parameter is applied globally, but once clicking elsewhere in storybook it will cause refreshes / flashes and whitescreens.

**Comment by pocka** [comment]
What version of Storybook are you using? Any console errors?

Probably the problem is outside of the figspec renderer (maybe in outermost addon logic or Storybook core?)

https://github.com/pocka/storybook-addon-designs/blob/release/v6.0/packages/storybook-addon-designs/src/register/components/Figspec.tsx#L82-L84

**Comment by shamilovtim** [comment]
> What version of Storybook are you using? Any console errors?
> 
> Probably the problem is outside of the figspec renderer (maybe in outermost addon logic or Storybook core?)
> 
> https://github.com/pocka/storybook-addon-designs/blob/release/v6.0/packages/storybook-addon-designs/src/register/components/Figspec.tsx#L82-L84
```
"storybook-addon-designs": "6.0.0-alpha.3",
"@storybook/addon-essentials": "6.2.0-rc.9",
"@storybook/react": "6.2.0-rc.9"
```

**Comment by shamilovtim** [comment]
Fixed. Required the withDesign decorator on the individual components for the whole system to work together.
